version: '3'
services:
  # postgres:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  buzzwords-web:
    build: 
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 3000:80
  mongo:
    image: mongo
    ports:
      - 27017:27017
