/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import flower02 from "../../assets/Flower02.glb";

export const Flower02 = ({ ...props }) => {
  const group = useRef();
  // @ts-ignore
  const { nodes, materials } = useGLTF(flower02);
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, Math.PI / 4, 0]}
        position={[0, 0, 1.2]}
        scale={0.41}
      >
        <mesh geometry={nodes.Flower02_1.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Flower02_2.geometry} material={materials.White} />
      </group>
    </group>
  );
};

useGLTF.preload(flower02);
