/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 SM_Icon_Watch_01.glb -tT 
Files: SM_Icon_Watch_01.glb [281.1KB] > SM_Icon_Watch_01-transformed.glb [40.37KB] (86%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import iconWatch01 from "../../assets/SM_Icon_Watch_01-transformed.glb?url";


type GLTFResult = GLTF & {
  nodes: {
    SM_Icon_Watch_01: THREE.Mesh
  }
  materials: {
    M_PolygonPrototype_01: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function IconWatch01(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(iconWatch01) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Icon_Watch_01.geometry} material={materials.M_PolygonPrototype_01} />
    </group>
  )
}

useGLTF.preload(iconWatch01)
