/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps, useFrame } from "@react-three/fiber";
import bee from "../../../assets/bee.gltf?url";
import { theme } from "../../theme";
import { Group } from "three";
console.log(bee);

// TODO: remove materials from model so we don't load unnecessary data
export const Bee = (props: GroupProps) => {
  const group = useRef<Group>();
  // @ts-ignore
  const { nodes } = useGLTF(bee);
  useFrame(({ clock }) => {
    if (group.current) {
      group.current.rotation.y = -1 * clock.getElapsedTime();
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, Math.PI / 4, -Math.PI / 1.5]}>
        <mesh geometry={nodes.Bee_1.geometry}>
          <meshStandardMaterial color={theme.colors.primary} />
        </mesh>
        <mesh geometry={nodes.Bee_2.geometry}>
          <meshStandardMaterial color={theme.colors.darkbrown} />
        </mesh>
        <mesh geometry={nodes.Bee_3.geometry}>
          <meshStandardMaterial color='#dddddd' />
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload(bee);
