version: '3'
services:
  # postgres:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
