/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Crown_1: THREE.Mesh
    Crown_2: THREE.Mesh
  }
  materials: {
    Crown: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Crown.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.89}>
        <mesh geometry={nodes.Crown_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Crown_2.geometry} material={materials.Red} />
      </group>
    </group>
  )
}

useGLTF.preload('/Crown.glb')
