name: Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t buzzwords-server:latest
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: buzzwords-server:latest
          image: buzzwords-server:latest
