name: Electron build
on: [push]
  # push:
  #   tags:
  #     - v*
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: 'yarn'
      - run: yarn build-electron && yarn dist
        working-directory: ./client

  # upload:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Release
  #       uses: fnkr/github-action-ghr@v1
  #       if: startsWith(github.ref, 'refs/tags/')
  #       env:
  #         GHR_COMPRESS: xz
  #         GHR_PATH: build/ # TODO TODO TODO
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
